### ISSUE TITLE
MatchWithWriters not present - hanging java clients

### ISSUE THREAD

**Issue by chandradeepak** [cockroachdb/cmux#5]
thanks for the connection multiplexer it is really useful . recently we found that java clients couldn't connect to our grpc server . I see this issue is fixed in https://github.com/soheilhy/cmux and we have MatchWithWriters present there . So it works with it. But the repo here doesn't have that function . When is that going to merge with this cockroachdb cmux.

or which one do you recommend using https://github.com/soheilhy/cmux  or https://github.com/cockroachdb/cmux/

Please advise. 

Also if i use java client with tls and and a go server with tls it hangs even if i set 
grpcl := m.MatchWithWriters(cmux.HTTP2MatchHeaderFieldSendSettings("content-type", "application/grpc"))

If i dont use tls for authentication then it works.  We have wrapped the tls over cmux so tls would be happening first. Is there any workaround for that ?

Thanks

**Comment by tamird** [comment]
Indeed. If you require this feature, you'll need to use @soheilhy's cmux. See https://github.com/cockroachdb/cockroach/commit/7017b820dee13c51e0e44aee88c06314ef801873 where we worked around this in CockroachDB in a different way.

**Comment by chandradeepak** [comment]
Thanks for the info. Not only i had to use the  @soheilhy's cmux for the tls with java clients i had to have tls listener started first and then pass that listener for cmux. 
And for the tls connection with from a java client i had to enable alpn authentication 

`tlsConfig.NextProtos = append(tlsConfig.NextProtos, http2.NextProtoTLS)
newln := tls.NewListener(ln, tlsConfig)` for the listener created.

At java grpc end i had to use netty tcnative for ssl as mentioned in 
[https://github.com/grpc/grpc-java/blob/master/SECURITY.md]

```
 `<artifactId>netty-tcnative-boringssl-static</artifactId>
    <version>1.1.33.Fork17</version>`
```

as the artifact.

`ManagedChannel    originChannel = NettyChannelBuilder.forAddress(host, port)
                    .sslContext(GrpcSslContexts.forClient().trustManager(new File("root.pem")).build())
                    .build();`
